spring:
  application:
    name: api-gateway
  sleuth:
    enabled: true
    sampler:
      probability: 1.0  # Captura todos os traces para fins de demonstração
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'